import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "rgba(24,25,26,1)" },

  // Header
  headerBlock: {
    backgroundColor: "rgba(44,44,49,1)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 8,
    marginBottom: 24,
  },
  avatar: {
    width: 79,
    height: 79,
    borderRadius: 40,
    backgroundColor: "#0075FF",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
  },
  avatarImage: { width: 79, height: 79, borderRadius: 40 },
  avatarText: {
    color: "#FFFFFF",
    fontFamily: "Roboto",
    fontWeight: "700",
    fontSize: 30,
    lineHeight: 30,
  },
  editIcon: {
    position: "absolute",
    bottom: -2,
    right: -2,
    backgroundColor: "rgba(44,44,49,1)",
    borderRadius: 16,
    padding: 4,
  },
  userName: {
    marginLeft: 44,
    color: "#FFFFFF",
    fontFamily: "Roboto",
    fontWeight: "700",
    fontSize: 30,
    lineHeight: 30,
  },
  logoutButton: { marginLeft: "auto", marginRight: 16 },

  // Section blocks
  sectionBlock: {
    backgroundColor: "rgba(44,44,49,1)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    paddingVertical: 16,
    paddingHorizontal: 8,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 16,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 60,
  },
  sectionTitle: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 24,
    color: "#FFFFFF",
    lineHeight: 24,
  },
  sectionSubtitle: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 18,
    color: "#FFFFFF",
    opacity: 0.8,
    marginTop: 6,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(227,227,227,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginHorizontal: 35,
    marginVertical: 16,
  },
  itemsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 12,
  },
  characterSquare: { borderRadius: 8 },
  addSquare: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(227,227,227,1)",
    justifyContent: "center",
    alignItems: "center",
  },
  worldRect: { borderRadius: 8 },
  addRect: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(227,227,227,1)",
    justifyContent: "center",
    alignItems: "center",
  },
});
